---
language: python
python: "3.6"

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Install pyATS
  - pip install pyats

  # Install Genie
  - pip install genie

  # Install yamllint
  - pip install yamllint

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../\nfilter_plugins=../filter_plugins' >ansible.cfg

script:
  # Yaml Linting. Gotta get that 5/5 code quality score.
  - yamllint -c ymllint_config.yml *
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax
  # Test the parser functionality in a playbook
  - ansible-playbook tests/test.yml --connection=local -i tests/inventory

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
