---
language: python
python: "3.6"

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Install Genie
  - pip install genie

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../\nfilter_plugins=../filter_plugins' >ansible.cfg

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax
  - ansible-playbook tests/test.yml --connection=local -i tests/inventory

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/